In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#loading dataset
df = pd.read_excel('Business_Funding_Data.xlsx')

In [3]:
# pip install openpyxl 
# Used to support the opening of .xlsx file

In [4]:
#Viewing the first 5 rows of the dataset
df.head()

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...

In [5]:
# summary if the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     str
 1   Effective date             6 non-null      str
 2   Found At                   26 non-null     str
 3   Financing Type             8 non-null      str
 4   Financing Type Normalized  8 non-null      str
 5   Categories                 26 non-null     str
 6   Investors                  13 non-null     str
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     str
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     str
dtypes: float64(1), int64(1), str(9)
memory usage: 2.4 KB

In [6]:
#number of rows
len(df)

26

In [7]:
# Percentage of missing values
missing_percentage = df.isnull().sum()/len(df)*100
missing_percentage

Website Domain                0.000000
Effective date               76.923077
Found At                      0.000000
Financing Type               69.230769
Financing Type Normalized    69.230769
Categories                    0.000000
Investors                    50.000000
Investors Count              50.000000
Amount                        0.000000
Amount Normalized             0.000000
Source Urls                   0.000000
dtype: float64

In [8]:
#dropping the 'effective date' column as it is irrelevant
df.drop(columns=('Effective date'), inplace=True)
df

,Website Domain,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-06-05T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-06-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [9]:
#dropping the 'Financing Type' column as it is irrelevant
df.drop(columns=('Financing Type'), inplace=True)
df

,Website Domain,Found At,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14T01:00:00+01:00,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31T02:00:00+02:00,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-07-24T02:00:00+02:00,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-05-01T02:00:00+02:00,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11T02:00:00+02:00,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24T02:00:00+02:00,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-08-07T02:00:00+02:00,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-07-08T02:00:00+02:00,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-18T02:00:00+02:00,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-03-26T01:00:00+01:00,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-05-09T02:00:00+02:00,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-07-16T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-07-15T02:00:00+02:00,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-06-05T02:00:00+02:00,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-06-27T02:00:00+02:00,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-25T02:00:00+02:00,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-10T02:00:00+02:00,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-18T02:00:00+02:00,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-06-25T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-30T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-05-22T02:00:00+02:00,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-06-25T02:00:00+02:00,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [10]:
#dropping the 'Found At' column as it is irrelevant
df.drop(columns=('Found At'), inplace=True)
df

,Website Domain,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [11]:
#Filling null entries in 'Financing Type Normalized' column with 'Not Provided'
df['Financing Type Normalized'] = df['Financing Type Normalized'].fillna('Not Provided')

In [12]:
df

,Website Domain,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,Not Provided,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,Not Provided,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,Not Provided,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,Not Provided,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,Not Provided,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,Not Provided,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,Not Provided,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,Not Provided,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,Not Provided,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,Not Provided,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,Not Provided,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,Not Provided,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,Not Provided,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,Not Provided,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,Not Provided,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,Not Provided,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,Not Provided,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,Not Provided,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [13]:
#Filling null entries in 'Investors' column with 'Not Provided'
df['Investors'] = df['Investors'].fillna('Not Provided')

In [14]:
df

,Website Domain,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,Not Provided,[],Not Provided,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,Not Provided,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,Not Provided,"[""private_equity""]",Not Provided,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,Not Provided,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,Not Provided,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,Not Provided,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,series_i,"[""series_i"", ""venture""]",Not Provided,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,Not Provided,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,Not Provided,[],Not Provided,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,seed,"[""seed"", ""venture""]",Not Provided,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,Not Provided,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,seed,"[""seed"", ""venture""]",Not Provided,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,Not Provided,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,Not Provided,[],Not Provided,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,series_a2,"[""series_a2"", ""venture""]",Not Provided,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,Not Provided,[],Not Provided,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,Not Provided,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,Not Provided,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,Not Provided,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,seed,"[""seed"", ""venture""]",Not Provided,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,Not Provided,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,seed,"[""seed"", ""venture""]",Not Provided,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,Not Provided,"[""private_equity"", ""venture""]",Not Provided,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,Not Provided,[],Not Provided,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [15]:
#Filling null entries in 'Investors Count' column with 'Zero'
df['Investors Count'] = df['Investors Count'].fillna(0)
df

,Website Domain,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,Not Provided,[],Not Provided,0.0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,Not Provided,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,Not Provided,"[""private_equity""]",Not Provided,0.0,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,Not Provided,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,Not Provided,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,Not Provided,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,series_i,"[""series_i"", ""venture""]",Not Provided,0.0,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,Not Provided,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,Not Provided,[],Not Provided,0.0,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,seed,"[""seed"", ""venture""]",Not Provided,0.0,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,Not Provided,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,seed,"[""seed"", ""venture""]",Not Provided,0.0,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,Not Provided,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,Not Provided,[],Not Provided,0.0,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,series_a2,"[""series_a2"", ""venture""]",Not Provided,0.0,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,Not Provided,[],Not Provided,0.0,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,Not Provided,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,Not Provided,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,Not Provided,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,seed,"[""seed"", ""venture""]",Not Provided,0.0,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,Not Provided,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,seed,"[""seed"", ""venture""]",Not Provided,0.0,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,Not Provided,"[""private_equity"", ""venture""]",Not Provided,0.0,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,Not Provided,[],Not Provided,0.0,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [16]:
#Filling null entries in 'Categories' column with 'Not Provided'
df['Categories'] = df['Categories'].replace('[]','["Not Provided"]')

In [17]:
df

,Website Domain,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,Not Provided,"[""Not Provided""]",Not Provided,0.0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,Not Provided,"[""Not Provided""]","avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,Not Provided,"[""private_equity""]",Not Provided,0.0,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,Not Provided,"[""Not Provided""]",stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,Not Provided,"[""Not Provided""]",chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,Not Provided,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,series_i,"[""series_i"", ""venture""]",Not Provided,0.0,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,Not Provided,"[""Not Provided""]",damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,Not Provided,"[""Not Provided""]",Not Provided,0.0,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,seed,"[""seed"", ""venture""]",Not Provided,0.0,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,Not Provided,"[""Not Provided""]",surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,seed,"[""seed"", ""venture""]",Not Provided,0.0,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,Not Provided,"[""Not Provided""]",eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,Not Provided,"[""Not Provided""]",Not Provided,0.0,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,series_a2,"[""series_a2"", ""venture""]",Not Provided,0.0,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,Not Provided,"[""Not Provided""]",Not Provided,0.0,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,Not Provided,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,Not Provided,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,Not Provided,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,seed,"[""seed"", ""venture""]",Not Provided,0.0,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,Not Provided,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,seed,"[""seed"", ""venture""]",Not Provided,0.0,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,Not Provided,"[""private_equity"", ""venture""]",Not Provided,0.0,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,Not Provided,"[""Not Provided""]",Not Provided,0.0,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [18]:
#Checking duplicate rows
duplicates = df.duplicated().sum()
print(duplicates)

0

In [19]:
#Confirming if there are no more null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     str
 1   Financing Type Normalized  26 non-null     str
 2   Categories                 26 non-null     str
 3   Investors                  26 non-null     str
 4   Investors Count            26 non-null     float64
 5   Amount                     26 non-null     str
 6   Amount Normalized          26 non-null     int64
 7   Source Urls                26 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.8 KB

In [20]:
#All null values have been well handled, data is ready for further analysis
# Export the cleaned dataset to a new CSV file
df.to_csv('cleaned_Business_Funding_Data.csv', index=False)
print("Cleaned dataset exported to 'cleaned_Business_Funding_Data.csv'")

Cleaned dataset exported to 'cleaned_Business_Funding_Data.csv'